#!/bin/bash

VIP_IFACE="$(/usr/sbin/route |grep default |head -1|awk '{print $8}')"
VIP="$(/usr/sbin/ifconfig $DROP_VIP_IFACE:0 | grep 'inet '| awk '{ print $2}')"

docker run --rm -i -u root -w /home/drop-core/ -p 8084:8084 -v /var/lib/drop:/var/lib/drop -m 100m -e HOSTNAME=$VIP webbone:0.1.0 ./start
