#!/bin/bash

source ~/.bashrc


if [ "x" != "x$DROP_AWS_EIP" ] 
then
    VIP=$DROP_AWS_EIP
else

    if [ "x" == "x$DROP_IFACE" ]                                                    
    then                                                                            
        VIP_IFACE="$(/sbin/route |grep default |head -1|awk '{print $8}')" 
    else                                                                            
        VIP_IFACE=$DROP_IFACE
    fi                                                                              

    VIP="$(/sbin/ifconfig $VIP_IFACE:0 | grep 'inet '| awk '{ print $2}')"

    if [ "x" == "x$VIP" ]
    then
        sleep 10
        exit 0
    fi        

fi

HUID=$(id -u drop-core)

docker run --rm -i --name webbone --privileged -u root -w /home/drop-core/ --net=host -v /var/lib/drop:/var/lib/drop -m 100m -e HOSTNAME=$VIP -e HUID=$HUID webbone:0.1.0 ./start
